import {
  IconGauge,
  IconCalendarEvent,
  IconHeartHandshake,
  IconNews,
  IconSpeakerphone,
  IconUsers,
  IconSettings,
  IconLogout,
  IconSchool,
  IconCamper,
  IconBuilding,
  IconBuildingFortress,
  IconBuildings,
  IconFolder,
  IconCamera,
  IconPhotoPlus,
  IconBriefcase,
  IconCertificate,
  IconPhoneCall,
  IconAmbulance,
  IconPhoneCalling,
  IconUser,
  IconPaperBag,
  IconWallpaper,
  IconRobot,
  IconBaselineDensityMedium,
  IconListDetails,
  IconNumber,
  IconNotebook,
  IconFlag3,
  IconMail,
} from "@tabler/icons-react";
import { Roles } from "./roles";

export const menu = {
  mainMenu: [
    {
      label: "Dashboard",
      icon: IconGauge,
      link: "/dashboard",
    //   permissions: [],
    },
    {
      label: "News",
      icon: IconNews,
      link: "/news",
      permissions: [
        Roles.SUPER_ADMIN,
        // Roles.CAMPUS_ADMIN,
        Roles.COLLEGE_ADMIN,
        Roles.EDITOR,
        Roles.INSTITUTE_ADMIN,
        Roles.TOP_EDITOR,
      ],
      links: [
        {
          label: "News",
          icon: IconNews,
          link: "/news",
          permissions: [
            Roles.SUPER_ADMIN,
            // Roles.CAMPUS_ADMIN,
            Roles.COLLEGE_ADMIN,
            Roles.EDITOR,
            Roles.INSTITUTE_ADMIN,
            Roles.TOP_EDITOR,
          ],
        },
        {
          label: "Approval Requests",
          icon: IconBaselineDensityMedium,
          link: "/approvals/news",
          permissions: [Roles.SUPER_ADMIN, Roles.TOP_EDITOR],
        },
      ],
    },
    {
      label: "Announcements",
      icon: IconSpeakerphone,
      link: "/announcements",
      permissions: [
        Roles.SUPER_ADMIN,
        // Roles.CAMPUS_ADMIN,
        Roles.COLLEGE_ADMIN,
        Roles.EDITOR,
        Roles.INSTITUTE_ADMIN,
        Roles.TOP_EDITOR,
      ],
      links: [
        {
          label: "Announcements",
          icon: IconSpeakerphone,
          link: "/announcements",
          permissions: [
            Roles.SUPER_ADMIN,
            // Roles.CAMPUS_ADMIN,
            Roles.COLLEGE_ADMIN,
            Roles.EDITOR,
            Roles.INSTITUTE_ADMIN,
            Roles.TOP_EDITOR,
          ],
        },
        {
          label: "Approval Requests",
          icon: IconBaselineDensityMedium,
          link: "/approvals/announcements",
          permissions: [Roles.SUPER_ADMIN, Roles.TOP_EDITOR],
        },
      ],
    },
    {
      label: "Events",
      icon: IconCalendarEvent,
      link: "/events",
      permissions: [
        Roles.SUPER_ADMIN,
        // Roles.CAMPUS_ADMIN,
        Roles.COLLEGE_ADMIN,
        Roles.EDITOR,
        Roles.INSTITUTE_ADMIN,
        Roles.TOP_EDITOR,
      ],
      links: [
        {
          label: "Events",
          icon: IconCalendarEvent,
          link: "/events",
          permissions: [
            Roles.SUPER_ADMIN,
            // Roles.CAMPUS_ADMIN,
            Roles.COLLEGE_ADMIN,
            Roles.EDITOR,
            Roles.INSTITUTE_ADMIN,
            Roles.TOP_EDITOR,
          ],
        },
        {
          label: "Approval Requests",
          icon: IconBaselineDensityMedium,
          link: "/approvals/events",
          permissions: [Roles.SUPER_ADMIN, Roles.TOP_EDITOR],
        },
      ],
    },
    {
      label: "Users",
      icon: IconUsers,
      link: "/users",
      permissions: [
        Roles.SUPER_ADMIN,
        Roles.COLLEGE_ADMIN,
        Roles.INSTITUTE_ADMIN,
      ],
      links: [
        {
          label: "Users",
          icon: IconUsers,
          link: "/users",
          permissions: [
            Roles.SUPER_ADMIN,
            Roles.COLLEGE_ADMIN,
            Roles.INSTITUTE_ADMIN,
          ],
        },
        {
          label: "Approval Requests",
          icon: IconBaselineDensityMedium,
          link: "/approval",
          permissions: [Roles.SUPER_ADMIN],
        },
      ],
    },
    {
      label: "Partnerships",
      icon: IconCalendarEvent,
      link: "/partnerships",
      permissions: [
        Roles.SUPER_ADMIN,
        // Roles.CAMPUS_ADMIN,
        Roles.COLLEGE_ADMIN,
        Roles.EDITOR,
        Roles.INSTITUTE_ADMIN,
        Roles.TOP_EDITOR,
      ],
      links: [
        {
          label: "Partnerships",
          icon: IconCalendarEvent,
          link: "/partnerships",
          permissions: [
            Roles.SUPER_ADMIN,
            // Roles.CAMPUS_ADMIN,
            Roles.COLLEGE_ADMIN,
            Roles.EDITOR,
            Roles.INSTITUTE_ADMIN,
            Roles.TOP_EDITOR,
          ],
        },
        {
          label: "Approval Requests",
          icon: IconBaselineDensityMedium,
          link: "/approvals/partnerships",
          permissions: [Roles.SUPER_ADMIN, Roles.TOP_EDITOR],
        },
      ],
    },
    {
      label: "Programs",
      icon: IconListDetails,
      link: "/programs",
      permissions: [
        Roles.SUPER_ADMIN,
        Roles.CAMPUS_ADMIN,
        // Roles.COLLEGE_ADMIN,
        // Roles.EDITOR,
        // Roles.INSTITUTE_ADMIN,
      ],
    },
    {
      label: "Organizations",
      icon: IconBuilding,
      permissions: [Roles.SUPER_ADMIN],
      links: [
        {
          label: "Colleges",
          icon: IconSchool,
          link: "/colleges",
          permissions: [Roles.SUPER_ADMIN],
        },
        {
          label: "Campuses",
          icon: IconBuildingFortress,
          link: "/campuses",
          permissions: [Roles.SUPER_ADMIN],
        },
        {
          label: "Institutes",
          icon: IconBuilding,
          link: "/institutes",
          permissions: [Roles.SUPER_ADMIN],
        },
      ],
    },
    {
      label: "Academic Units",
      icon: IconBuildings,
      links: [
        {
          label: "Units",
          icon: IconBuildings,
          link: "/units",
          permissions: [
            Roles.SUPER_ADMIN,
            // Roles.CAMPUS_ADMIN,
            Roles.COLLEGE_ADMIN,
            Roles.INSTITUTE_ADMIN,
          ],
        },
        {
          label: "Unit's Pages",
          icon: IconPaperBag,
          link: "/units-pages",
          permissions: [
            Roles.SUPER_ADMIN,
            // Roles.CAMPUS_ADMIN,
            Roles.COLLEGE_ADMIN,
            Roles.INSTITUTE_ADMIN,
          ],
        },
      ],
      permissions: [
        Roles.SUPER_ADMIN,
        // Roles.CAMPUS_ADMIN,
        Roles.COLLEGE_ADMIN,
        Roles.INSTITUTE_ADMIN,
      ],
    },
    {
      label: "Statistics",
      icon: IconNumber,
      link: "/statistics",
      permissions: [Roles.SUPER_ADMIN],
    },
    {
      label: "Publications",
      icon: IconNotebook,
      link: "/publications",
      permissions: [
        Roles.SUPER_ADMIN,
        // Roles.CAMPUS_ADMIN,
        Roles.COLLEGE_ADMIN,
        Roles.EDITOR,
        Roles.INSTITUTE_ADMIN,
        Roles.TOP_EDITOR,
      ],
      links: [
        {
          label: "Publications",
          icon: IconNotebook,
          link: "/publications",
          permissions: [
            Roles.SUPER_ADMIN,
            // Roles.CAMPUS_ADMIN,
            Roles.COLLEGE_ADMIN,
            Roles.EDITOR,
            Roles.INSTITUTE_ADMIN,
            Roles.TOP_EDITOR,
          ],
        },
        {
          label: "Approval Requests",
          icon: IconBaselineDensityMedium,
          link: "/approvals/publications",
          permissions: [Roles.SUPER_ADMIN, Roles.TOP_EDITOR],
        },
      ],
    },
    {
      label: "Documents",
      icon: IconBriefcase,
      link: "/documents",
      permissions: [Roles.SUPER_ADMIN],
    },
    {
      label: "Gallery & Photos",
      icon: IconPhotoPlus,
      permissions: [
        Roles.SUPER_ADMIN,
      ],
      links: [
        {
          label: "Gallery",
          icon: IconPhotoPlus,
          link: "/gallery",
          permissions: [
            Roles.SUPER_ADMIN,
          ],
        },
      ],
    },
    {
      label: "Leaderships",
      icon: IconCertificate,
      permissions: [Roles.SUPER_ADMIN],
      links: [
        {
          label: "Leadership",
          icon: IconCertificate,
          link: "/leaderships",
          permissions: [Roles.SUPER_ADMIN],
        },
        {
          label: "Presidents",
          icon: IconCertificate,
          link: "/presidents",
          permissions: [Roles.SUPER_ADMIN],
        },
        {
          label: "President Speeches",
          icon: IconSpeakerphone,
          link: "/president-speeches",
          permissions: [Roles.SUPER_ADMIN],
        },
      ],
    },
    {
      label: "Contacts",
      icon: IconPhoneCall,
      permissions: [
        Roles.SUPER_ADMIN,
      ],
      links: [
        {
          label: "Contacts",
          icon: IconPhoneCalling,
          link: "/contacts",
          permissions: [
            Roles.SUPER_ADMIN,
          ],
        },
        {
          label: "Emergencies",
          icon: IconAmbulance,
          link: "/emergencies",
          permissions: [
            Roles.SUPER_ADMIN,
          ],
        },
      ],
    },
    {
      label: "Page Builder",
      icon: IconWallpaper,
      link: "/page-builder",
      permissions: [Roles.SUPER_ADMIN],
    },
    {
      label: "Chatbot Trainer",
      icon: IconRobot,
      link: "/chatbot",
      permissions: [Roles.SUPER_ADMIN],
    },
    {
      label: "Calendar",
      icon: IconCalendarEvent,
      link: "/calendar",
      permissions: [
        Roles.SUPER_ADMIN,
      ],
    },
    {
      label: "Subscribers",
      icon: IconMail,
      link: "/subscribers",
      permissions: [Roles.SUPER_ADMIN, Roles.TOP_EDITOR],
    },
    {
      label: "Banner",
      icon: IconFlag3,
      link: "/banner",
      permissions: [Roles.SUPER_ADMIN, Roles.TOP_EDITOR],
    },
  ],
  Others: [
    {
      label: "Profile",
      icon: IconUser,
      link: "/profile",
      permissions: [
        Roles.CAMPUS_ADMIN,
        Roles.COLLEGE_ADMIN,
        Roles.STAFF,
        Roles.SUPER_ADMIN,
        Roles.EDITOR,
        Roles.TOP_EDITOR,
      ],
    },
    {
      label: "Settings",
      icon: IconSettings,
      link: "/settings",
      permissions: [
        Roles.CAMPUS_ADMIN,
        Roles.COLLEGE_ADMIN,
        Roles.STAFF,
        Roles.SUPER_ADMIN,
        Roles.EDITOR,
        Roles.INSTITUTE_ADMIN,
        Roles.TOP_EDITOR,
      ],
    },
    {
      label: "Log Out",
      icon: IconLogout,
      link: "/log-out",
      permissions: [
        Roles.CAMPUS_ADMIN,
        Roles.COLLEGE_ADMIN,
        Roles.STAFF,
        Roles.SUPER_ADMIN,
        Roles.EDITOR,
        Roles.INSTITUTE_ADMIN,
        Roles.TOP_EDITOR,
      ],
    },
  ],
};
