export enum Roles {
  SUPER_ADMIN = "SUPER_ADMIN",
  COLLEGE_ADMIN = "COLLEGE_ADMIN",
  CAMPUS_ADMIN = "CAMPUS_ADMIN",
  STAFF = "STAFF",
  EDITOR = "EDITOR",
  INSTITUTE_ADMIN = "INSTITUTE_ADMIN",
  TOP_EDITOR = "TOP_EDITOR",
}
